# Generated by Django 3.0.7 on 2020-06-06 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import initiative.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiative', '0003_delete_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_text', models.TextField(verbose_name='Текст обращения')),
                ('initiative_type', models.CharField(choices=[('appeal', 'Обращение'), ('complaint', 'Жалоба')], default='appeal', max_length=9, verbose_name='Тип')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_category', to='initiative.Category')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InitiativePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', initiative.models.NamedImageField(upload_to='uploads/initiative', verbose_name='photo')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_photo', to='initiative.Initiative')),
            ],
        ),
    ]
