# Generated by Django 3.0.7 on 2020-06-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiative', '0004_initiative_initiativephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
