# Generated by Django 3.0.7 on 2020-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0005_initiative_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='name',
            field=models.CharField(default=' ', max_length=300, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
