# Generated by Django 3.0.7 on 2020-06-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_geo'),
        ('users', '0002_auto_20200606_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_geo', to='initiative.Geo'),
        ),
    ]
