# Generated by Django 3.0.7 on 2020-06-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200606_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профессия'),
        ),
    ]
