# Generated by Django 3.0.7 on 2020-06-06 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiative', '0005_initiative_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_vote', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_vote_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('leader', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InitiativeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_vote', to='initiative.Initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_vote_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('initiative', 'user')},
            },
        ),
    ]
