# Generated by Django 3.0.7 on 2020-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='lat',
            field=models.CharField(blank=True, max_length=9, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='geo',
            name='long',
            field=models.CharField(blank=True, max_length=9, verbose_name='Долгота'),
        ),
    ]
